DROP TABLE IF EXISTS sellers CASCADE;
DROP TABLE IF EXISTS vehicles CASCADE;
DROP TABLE IF EXISTS dealers CASCADE;
DROP TABLE IF EXISTS auctions CASCADE;
DROP TABLE IF EXISTS images CASCADE;
DROP TABLE IF EXISTS transactions CASCADE;
CREATE TABLE sellers (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255),
  password VARCHAR(255)
);

CREATE TABLE vehicles (
  id SERIAL PRIMARY KEY NOT NULL,
  seller_id INTEGER REFERENCES sellers(id) ON DELETE CASCADE,
  Maker VARCHAR(255),
  Model VARCHAR(255),
  Year int NOT NULL,
  Milage int NOT NULL,
  Sell_Status BOOLEAN DEFAULT FALSE,
  Approve_Status BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT Now()
);

CREATE TABLE dealers (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255)
);

CREATE TABLE auctions (
  id SERIAL PRIMARY KEY NOT NULL,
  vehicle_id INTEGER REFERENCES vehicles(id) ON DELETE CASCADE,
  dealer_id INTEGER REFERENCES dealers(id) ON DELETE CASCADE,
  price int,
  selected BOOLEAN DEFAULT FALSE
);

CREATE TABLE images (
  id SERIAL PRIMARY KEY NOT NULL,
  vehicle_id INTEGER REFERENCES vehicles(id) ON DELETE CASCADE,
  source VARCHAR (255)
);

CREATE TABLE transactions (
  id SERIAL PRIMARY KEY NOT NULL,
  vehicle_id INTEGER REFERENCES vehicles(id) ON DELETE CASCADE,
  dealer_id INTEGER REFERENCES dealers(id) ON DELETE CASCADE,
  price int NOT NULL,
  selected BOOLEAN DEFAULT FALSE
);